image: node:10.15.3

pipelines:
  branches:
    master:
      - step:
          name: Install, build and tests
          services:
            - docker
          caches:
            - docker
            - node
            - npm
          script:
            - npm install
            - CI=false npm run build
          artifacts:
            - build/**
      - step:
          name: Deploy to S3
          services:
            - docker
          caches:
            - docker
          deployment: production
          script:
            - pipe: atlassian/aws-s3-deploy:0.2.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $PRODUCTION_BUCKET_NAME
                LOCAL_PATH: "build"
      - step:
          name: Clear Cloudfront Cache
          services:
            - docker
          caches:
            - docker
          script:
            - pipe: atlassian/aws-cloudfront-invalidate:0.1.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                DISTRIBUTION_ID: $PRODUCTION_DISTRIBUTION_ID

definitions:
  caches:
    npm: $HOME/.npm